### ISSUE TITLE
Many warnings generated after running concatenateProjectGraphs

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/fimsR-access#1]
Lots of warnings generated after running the dipnet graphs.

Some of the warning messages look like:

> warnings();
> Warning messages:
> 1: In `[<-.factor`(`*tmp*`, ri, value = c(3099.05, 1538.06,  ... :
>   invalid factor level, NA generated
> 2: In `[<-.factor`(`*tmp*`, ri, value = c(3099.05, 1538.06,  ... :
>   invalid factor level, NA generated
> 3: In `[<-.factor`(`*tmp*`, ri, value = c(1523L, 4859L, 1519L,  ... :

**Comment by rodney757** [comment]
this is no longer applicable with the latest updates
