### ISSUE TITLE
df <- queryMetadata() does not work

### ISSUE THREAD

**Issue by afredston** [biocodellc/fimsR-access#2]
Thank you so much for developing this tool - I'm really interested in using it! I'd like to access the entire database and then filter it by location. However, when I try to fetch all samples in the database, I get the following error: 

```
> fulldf <- queryMetadata()
[1] "No Samples Found"
> markers <- listMarkers()
> expeditionsList <- listExpeditions()
```

As you can see, the other queries work fine, but the object `fulldf` is empty. I had this issue both with the CRAN and development versions of `geomedb`. I can brute force a solution as follows, but it would miss any data entry without an assigned expedition (not sure if that is an issue with this database):

```
> expeditionsList <- listExpeditions()
> fulldf2 <- queryMetadata(expeditions=expeditionsList)
```

Let me know what you think, and thanks again!

**Comment by rodney757** [comment]
I can't remember off the top of my head exactly how the queryMetadata query
works... I'll take a closer look in the next day or two.

however, all datasets must have an expedition, so your fulldf2 query won't
miss anything.

**Comment by afredston** [comment]
Awesome! In that case I'll proceed with the df I extracted. Thanks again.

**Comment by rodney757** [comment]
fixed in https://github.com/biocodellc/fimsR-access/commit/c3b2ca5ae5c1edb49eaad470b79166e171cf248f
